# Generated by Django 5.0.4 on 2024-06-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='family',
            new_name='FullName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='Password',
            field=models.IntegerField(null=True),
        ),
    ]
