# Generated by Django 5.0.4 on 2024-06-08 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='IP',
            field=models.CharField(max_length=100, null=True, verbose_name='آیپی کابر'),
        ),
    ]
