# Generated by Django 5.0.4 on 2024-06-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_user_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customermessage',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200, null=True, verbose_name='ایمیل')),
                ('Issue', models.CharField(max_length=200, null=True)),
                ('message', models.TextField(max_length=200, verbose_name='پیام')),
            ],
        ),
    ]
