# Generated by Django 5.0.4 on 2024-06-12 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_customermessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomerUser',
        ),
    ]
