# Generated by Django 5.0.4 on 2024-06-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_rename_user_customeruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
