# Generated by Django 5.0.4 on 2024-06-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0007_customeruser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='username',
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='FullName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customeruser',
            name='UserName',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
